---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Creates directory for cert
  file: path=/etc/pki/tls/certs state=directory owner=root group=root mode=0775 recurse=yes

- name: copy the cert filebeat
  copy: src=../../../defaults/filebeat.my dest=/etc/pki/tls/certs/logstash-forwarder.crt owner=root group=root mode=644

- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true
